version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Senha123
      MYSQL_DATABASE: meubanco
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - app_net

  web1:
    build: ./php
    container_name: web1
    volumes:
      - ./php:/var/www/html
    depends_on:
      - mysql
    networks:
      - app_net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "4500:4500"
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
